version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.0
      - image: mysql:8.0.0
        environment:
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: hub_board_test
    working_directory: ~/hub-board
    steps:
      - checkout
      - run:
          name: Library install
          command: apt-get update && apt-get install ruby-uglifier
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace RAILS_ENV=test
      - run:
          name: DB Migrations
          command: bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: Run Tests
          command: bundle exec rspec -p spec/
