version: 2
jobs:
  build:
  build:
    working_directory: ~/
    docker:
      - image: ruby:2.4.0
      - image: mysql:8.0.0
        environment:
            MYSQL_USER: mysql
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: hub_board_test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Create DB
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: DB Migrations
          command: bundle exec rake db:migrate
      - run:
          name: Run Tests
          command: bundle exec rspec -p spec/
