version: "3"
services:
  web:
    build: .
    image: hub-board
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/var/app
      - /var/app/vendor
    links:
      - rdb
  rdb:
    image: mysql:8.0.0
    env_file: .docker/mysql/env
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/conf.d:/etc/mysql/conf.d
