default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: mysql
  password: mysql 
  host: rdb
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hub-board_development

test:
  <<: *default
  database: hub-board_test

production:
  <<: *default
  datebase: hub-board_production
