default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  username: mysql
  password: mysql 
  host: rdb
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: hub_board_development

test:
  <<: *default
  database: hub_board_test

production:
  <<: *default
  datebase: hub_board_production
